version: '3'

networks:
  mumble_mumo:

services:
  murmur:
    build: mumble_snapshot
    restart: always
    volumes:
      - /srv/docker_volumes/murmur/data:/home/murmur/data
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
      - "6502"
    networks:
      - mumble_mumo

  mumo:
    build: mumo_alpine
    restart: always
    volumes:
      - /srv/docker_volumes/mumo/data:/home/mumo/data
#    ports:
#      - 6502
    networks:
      - mumble_mumo

#volumes:
#  - /srv/docker_volumes/murmur

#vim: tabstop=2 shiftwidth=2 expandtab
