version: '3.2'

networks:
  mumble_mumo:

services:
  murmur:
    build: mumble_snapshot
    restart: always
    volumes:
      - type: volume
        source: mumble-data
        target: /home/murmur/data
      - type: volume
        source: mumble-share
        target: /home/murmur/share
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
      - "6502"
    networks:
      - mumble_mumo
    cap_drop:
      - ALL

  mumo:
    build: mumo_alpine
    restart: always
    volumes:
      - /srv/docker_volumes/mumo/modules_enabled:/home/mumo/modules_enabled
      - /srv/docker_volumes/mumo/mumo.ini:/home/mumo/mumo.ini
      - mumble-share:/home/mumo/share
    depends_on:
      - murmur

# uncomment the next two lines to the the cloned addons stay
#    environment:
#      - DO_NOT_DELETE_ADDONS=true
    networks:
      - mumble_mumo

    cap_drop:
      - ALL

volumes:
  mumble-share:
  mumble-data:

#vim: tabstop=2 shiftwidth=2 expandtab
